# <center> Basic of Python <h3><a href = "https://www.linkedin.com/in/vipendrapal-rajput-3a0674160/" target = "_self">  Vipendra Pal Rajput </a></h3></center>

***

In [1]:
#casting 
# if you want to specify the data type variable this can be done by casting

x=3
print(type(x)) #check datatype
x=str(3)
print(type(x))


<class 'int'>
<class 'str'>


In [2]:
# case sensitive or latest value put

a=10
A=5
A=7
print(a)
print(A)
print(A)

10
7
7


In [3]:
#camel case 
# each word except the first start with capital letter

myVariableName = "John"

# Pascal case
# each word start with capital letter

MyVariableName = "John"

#snake case
#each word is seprate by underscore
my_variable_name = "John"

print(myVariableName)
print(MyVariableName)
print(my_variable_name)

John
John
John


In [4]:
# Pyhton  variable : assign multiple variable

x,y,z = "Orange", "Banana", "Cherry"
xyz = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)
print(xyz)

Orange
Banana
Cherry
('Orange', 'Banana', 'Cherry')


In [5]:
# Output variable
#The python print statement is often used to output variable

# to create both text and a variable python use the + charactor

x = "awasome"
y=3
y=str(3)

print("pythn is"+x)
print("pythn is"+y)
print("pythn is"+str(y))
print("pythn is",3)


pythn isawasome
pythn is3
pythn is3
pythn is 3


In [6]:
# taking input from user

a= int(input("enter first number"))
print(a)
b= int(input("enter second number"))
print(b)
c=a+b
print(c)
print(type(c))

enter first number56
56
enter second number44
44
100
<class 'int'>


In [7]:
# wheather an number is +VE or -VE or Zero

x=int(input("Please Enter any numeric number")) #take input from user
if x<0:                                         #apply conditions
    print("Entered number is Negetive")
elif x>0:
    print("Entered number is Positive")
else:
    print("Entered number is Zero")

Please Enter any numeric number-67
Entered number is Negetive


In [8]:
# wheather number is odd or even

x = int(input("Enter number : "))

if x%2 == 0:          # check reminder 
    print("Even")
else:
    print("Odd")

Enter number : 97
Odd


In [9]:
# Check number range between 0 to 100 and take 5 input from user and gave grade

while True:
    a = int(input("Enter 1st subject marks: "))
    if 100>= a >= 0:
        print(a)
        break

while True:
    b = int(input("Enter 2nd subject marks: "))
    if 100>= b >= 0:
        print(b)
        break

while True:
    c = int(input("Enter 3rd subject marks: "))
    if 100>= c >= 0:
        print(c)
        break
    
while True:
    d = int(input("Enter 4th subject marks: "))
    if 100>= d >= 0:
        print(d)
        break
while True:
    e = int(input("Enter 5th subject marks: "))
    if 100>= e >= 0:
        print(e)
        break
        
num = ((a+b+c+d+e)/500)*100          #Restore values and find percentage
print("Average Number : ",num)
print("\n")
if num <80:
    print("Average Number is : ",str(num) +" and Grade is D")
elif num>=95:
    print("Average Number is : ",str(num) +" and Grade is A")
elif num>=88:
    print("Average Number is : ",str(num) +" and Grade is B")
elif num>=80:
    print("Average Number is : ",str(num) +" and Grade is C")

Enter 1st subject marks: 99
99
Enter 2nd subject marks: 88
88
Enter 3rd subject marks: 89
89
Enter 4th subject marks: 92
92
Enter 5th subject marks: 93
93
Average Number :  92.2


Average Number is :  92.2 and Grade is B


In [10]:
# Python Identity operator
# Identity operator are used to compare the object

x = ["apple", "banaba"]
y = ["apple", "banaba"]
z = x
print(x is z)

#return true because it has same object

print(x is y)
# different object

print(x == y)
# compare return true because it equal to y

True
False
True


In [11]:
# Python membership operator
# membership operator used to test sequence is present in an object : in , not in
x = ["apple", "banana"]

print("kiwi" not in x)
print("kiwi" in x)

True
False


In [12]:
# calculate string length

a = "hello , world!"
c=0
for x in a:
    c+=1
print(c)

14


In [13]:
# Count an specific word how much times it comes

a="hello my name is xyz, my age is xyz, i work for xyz"
c=0
for x in a:
    if x is "z":
        c+=1
print(c)

3


In [14]:
#swap first and last charactor of string using slicing

a=input("Enter : ")
print(a[-1]+a[1:-1]+a[0])

Enter : Hello world!
!ello worldH


In [15]:
# Replace space using special charactor

a = input("Enter String : ")
a = a.replace(' ','@')
print(a)

Enter String : vipendra pal rajput
vipendra@pal@rajput


In [16]:
# Count charactor and word 

a = input("Enter : ")
c=0
d=0
for x in a:
    c+=1
    if x == " ":
        d+=1
print(d+1)
print(c)

Enter : hello user i am vipendra
5
24


In [17]:
#count charactor and digit with lower and upper

s="helloWORLD45"
c=0
d=0
t=0    
for x in s: 
    if x>='a'and x<='z': 
        c+=1                 
    if x>='A'and x<='Z': 
        d+=1
    if x>='0' and x<='9':
        t+=1
print(c) 
print(d)     
print(t)

5
5
2


In [18]:
#Reverse string using slicing

a="hell0 world"
a[::-1]

'dlrow 0lleh'

In [19]:
# Count number of elemnets in list
a = ["apple","banana", "cherry"]
c=0
for x in a:
    c+=1
print(c)

3


In [20]:
name = []    # take empty list
age = []
clas=[]
grade=[]
num = int(input("Enter How many students data you want to enter")) # take input from user 
for i in range(0,num): #In range of input
    while True:
        a = input("enter name : ")
        if a.isalpha() == True:
            #print(a)
            name.append(a)
            break
    while True:
        b = int(input("enter Age : "))
        if b>=20 and b<=40:
            #print(b)
            age.append(b)
            break

    while True:
        c = int(input("Grade : "))
        if c>=0 and c<=9:
            #print(c)
            grade.append(c)
            break
    while True:
        d = input("enter Class : ")
        e =len(d)
        if e ==4:
            d.isalnum()
            #print(d)
            clas.append(d)
            break
        

listss = name+age+grade+clas
print(listss)

for i in range(0,num):
    listt = "my name is {} and my age is {} and i get {} grade in class {}".format(name[i],age[i],grade[i],clas[i])
    print(listt)

Enter How many students data you want to enter2
enter name : Vipendra
enter Age : 22
Grade : 8
enter Class : IT94
enter name : Ajay
enter Age : 24
Grade : 9
enter Class : CS04
['Vipendra', 'Ajay', 22, 24, 8, 9, 'IT94', 'CS04']
my name is Vipendra and my age is 22 and i get 8 grade in class IT94
my name is Ajay and my age is 24 and i get 9 grade in class CS04


In [21]:
# Programme for bubble sort

a = [10,50,30,40,5]
b=len(a)
for i in range(0,b):
    for j in range(0,b-1):
        if(a[j] > a[j+1]):
            temp = a[j]
            a[j] = a[j+1]
            a[j+1] = temp
print(a)

[5, 10, 30, 40, 50]


In [22]:
#packing 
my_tuple = 3.6, "dog", 4
print(my_tuple)
#unpacking
a,b,c = my_tuple
print(a)
print(b)
print(c)

(3.6, 'dog', 4)
3.6
dog
4


In [23]:
#single variable is not tuple
a= 2
print(a)
#make single value tuple
m=("hello",)
print(m)
m = "hello",
print(m)

2
('hello',)
('hello',)


In [24]:
# insert element in list

def s(idx,el,lst):
    print(lst)
    lst1 = lst[:idx]
    lst1.append(el)
    lst1 +=lst[idx:]
    print(lst1)

idx=int(input("enter index"))
el=input("enter element")
lst=["vip","end","ra","pal"]
s(idx,el,lst)

enter index3
enter elementHive
['vip', 'end', 'ra', 'pal']
['vip', 'end', 'ra', 'Hive', 'pal']


In [25]:
#append list in another list

def s1(l,t):
    print(l[:]+[t])
l=["apple","banana"]
t=["SEEk","ACE","cherry","6"]
s1(l,t)

['apple', 'banana', ['SEEk', 'ACE', 'cherry', '6']]


In [26]:
# Extend another list

def s1(l,t):
    print(l[:]+t[:])
l=["apple","banana"]
t=["SEEk","ACE","cherry","6"]
s1(l,t)

['apple', 'banana', 'SEEk', 'ACE', 'cherry', '6']


In [27]:
# check length of the string without direct len function

a = ["apple","banana","mango","charry"]
c =0
while c!=len(a):
    c+=1
print(c)

4


In [28]:
# take input & check minimum input 5
def s():
    while True:
        a=input("enter string :") # take input from user
        b=a.split(" ")   #break string when we found space in string
        print(b)
        if len(b)>=5:
            break
s()

enter string :i am vipendra pal rajput
['i', 'am', 'vipendra', 'pal', 'rajput']


In [29]:
# take input & check minimum input 5 and nubering index on which number
def s():
    while True:
        a=input("enter string :") # take input from user
        b=a.split(" ")   #break string when we found space in string
        print(b)
        if len(b)>=5:
            for i in range(0,len(b)):
                print(i+1,b[i])  # print index and elements
            break
s()

enter string :i am vipendra
['i', 'am', 'vipendra']
enter string :i am vipendra pal rajput
['i', 'am', 'vipendra', 'pal', 'rajput']
1 i
2 am
3 vipendra
4 pal
5 rajput


In [30]:
# take input & check minimum input 5 and nubering index
def s():
    while True:
        a=input("enter string :") # take input from user
        b=a.split(" ")   #break string when we found space in string
        print(b)
        if len(b)>=5:
            for i in range(0,len(b)):
                print(i+1,len(b[i]),b[i])    # print index and elements
            break
s()

enter string :hello my name is vipen
['hello', 'my', 'name', 'is', 'vipen']
1 5 hello
2 2 my
3 4 name
4 2 is
5 5 vipen


In [31]:
users = ["abc","def","ghi","jkl"]
choice = ["1","2","3","4"]
for i in range(0,len(users)):
    t = "name of user is {} and have index {}".format(users[i],choice[i])
    print(t)

name of user is abc and have index 1
name of user is def and have index 2
name of user is ghi and have index 3
name of user is jkl and have index 4


In [32]:
users = ["abc","def","ghi","jkl"]
choice = ["1","2","3","4"]
for i in range(0,len(users)):
    t = "name of user is {1} and have index {0}".format(users[i],choice[i])
    print(t)

name of user is 1 and have index abc
name of user is 2 and have index def
name of user is 3 and have index ghi
name of user is 4 and have index jkl


***

### Sets {}

In [1]:
# a set is unordered or unindexed

a = {"a","b","c","d"}
print(a)

{'b', 'd', 'a', 'c'}


In [2]:
# set do not allow duplicate values

a={"a","b","a","d","e","r","d"}
print(a)
a.add("vip")
for x in a:
    print(a)

{'e', 'r', 'd', 'b', 'a'}
{'e', 'r', 'd', 'b', 'vip', 'a'}
{'e', 'r', 'd', 'b', 'vip', 'a'}
{'e', 'r', 'd', 'b', 'vip', 'a'}
{'e', 'r', 'd', 'b', 'vip', 'a'}
{'e', 'r', 'd', 'b', 'vip', 'a'}
{'e', 'r', 'd', 'b', 'vip', 'a'}


In [3]:
# apply union function to merge to sets but they arrenge in unordered format

set = {"a","b","c","d"}
set1={1,2,3}
set3 = set.union(set1)
print(set3)
print('\n')
# to remove repetated values from set we use intersection

set = {"a","b","c","d"}
set1={1,2,3,'a'}
set3 = set.union(set1)-set.intersection(set1)
print(set3)

print('\n')

# Print that is comman value in two sets

s={1,2,3,4,5}
s1={5,6,7,1,2}
print(s1.intersection(s))

{'b', 1, 2, 3, 'a', 'c', 'd'}


{1, 2, 3, 'c', 'd', 'b'}


{1, 2, 5}


In [1]:
# Count vowels on the bases of set

s=input("Please enter : ");
d=set("aeiouAEIOU")
c=0
for i in s:
    if i in d:
           c+=1;    
print(c)

Please enter : vipendraVIPENDRA
6


In [2]:
# Print that is not comman value in two sets

s={1,2,3,4,5}
s1={5,6,7,1,2}
s3 = set()
for i in s:
    if i not in s1:
        s3.add(i)
for i in s1:
    if i not in s:
        s3.add(i)
    
print(s3) 

{3, 4, 6, 7}


### Dictionary


In [3]:
# Print dictionary 

the = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
}
print(the)

{'brand': 'Ford', 'model': 'mustang', 'Year': 1999}


In [4]:
# Print dictionary value on the bases of keys

the = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
}
print(the["Year"])


# if we enter duplicate value in list then it take latest value by default

the = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
    "Year":1988
}
print(the)
print(the["Year"])


# Dictionary contains all string int boolean and list inside dict

the = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
    "elc":True,
    "Year":1988,
    "colors":["red","blac"]
}
print(the)

1999
{'brand': 'Ford', 'model': 'mustang', 'Year': 1988}
1988
{'brand': 'Ford', 'model': 'mustang', 'Year': 1988, 'elc': True, 'colors': ['red', 'blac']}


In [5]:
# Updeting keys
car = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
    "Year":1988
}
x=car.keys()
y=car.values()

print(x)
print(y)
car["color"]="white"

x=car.keys()
y=car.values()

print(x)
print(y)


dict_keys(['brand', 'model', 'Year'])
dict_values(['Ford', 'mustang', 1988])
dict_keys(['brand', 'model', 'Year', 'color'])
dict_values(['Ford', 'mustang', 1988, 'white'])


In [6]:
# access items
# Updeting keys
car = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
    "Year":1988
}
x=car.items()

print(x)
car["Year"]=2020

print(x)

dict_items([('brand', 'Ford'), ('model', 'mustang'), ('Year', 1988)])
dict_items([('brand', 'Ford'), ('model', 'mustang'), ('Year', 2020)])


In [7]:
for x in car:
    print(x)
    
print('\n')

for x in car:
    print(car[x])
    
    
print('\n')

for x in car:
    print(x,car[x])
    
print('\n')

for x in car.items():
    print(x)
    
print('/n')

for x,y in car.items():
    print(x,y)

brand
model
Year


Ford
mustang
2020


brand Ford
model mustang
Year 2020


('brand', 'Ford')
('model', 'mustang')
('Year', 2020)
/n
brand Ford
model mustang
Year 2020


In [8]:
car = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
    "Year":1988
}
mycar = car.copy()
print(mycar)

{'brand': 'Ford', 'model': 'mustang', 'Year': 1988}


In [9]:
myfam = {
    "child":{
        "name":"Email",
        "year":2004
    },
    "child1":{
        "name":"tobias",
        "year":2006
    },
    "child2":{
        "name":"tins",
        "year":2011
    },
}


print(myfam)
print("\n")
print(myfam.values())
print("\n")

print(myfam.keys())
print("\n")

print(myfam.items())

{'child': {'name': 'Email', 'year': 2004}, 'child1': {'name': 'tobias', 'year': 2006}, 'child2': {'name': 'tins', 'year': 2011}}


dict_values([{'name': 'Email', 'year': 2004}, {'name': 'tobias', 'year': 2006}, {'name': 'tins', 'year': 2011}])


dict_keys(['child', 'child1', 'child2'])


dict_items([('child', {'name': 'Email', 'year': 2004}), ('child1', {'name': 'tobias', 'year': 2006}), ('child2', {'name': 'tins', 'year': 2011})])


In [10]:
child = {
    "name":"Email",
    "year":2004
}
child1= {
    "name":"tobias",
    "year":2006
}
child2 = {
    "name":"tins",
    "year":2011
}
myfam={
    "c1" :child,
    "c2":child1,
    "c3": child2
}


print(myfam)
print("\n")


{'c1': {'name': 'Email', 'year': 2004}, 'c2': {'name': 'tobias', 'year': 2006}, 'c3': {'name': 'tins', 'year': 2011}}




In [11]:
# take input and pair them as the key and values

key = input("enyter added")
value = input("enter grade  value")
d={}
d.update({key:value})
print(d)

enyter addedvipenra
enter grade  value8
{'vipenra': '8'}


In [12]:
# take input from user to enter in dictionary key and values

num = int(input("enter how many entry you want to enter"))
d={}
for i in range(0,num):
    key = input("enyter keys : ")
    value = input("enter values : ")
    d.update({key:value})
    print(d)

enter how many entry you want to enter3
enyter keys : Vipen
enter values : 7
{'Vipen': '7'}
enyter keys : ajay
enter values : 8
{'Vipen': '7', 'ajay': '8'}
enyter keys : harsh
enter values : 3
{'Vipen': '7', 'ajay': '8', 'harsh': '3'}


In [13]:
# Merge to dictionay on the bases of key & value pairs
x=["a","b","c"]
v=[1,2,3]
d=dict(zip(x,v))
print(d)

{'a': 1, 'b': 2, 'c': 3}


In [14]:
# Enter Name and last name and capital first letter and enter marks and grade

#num = int(input("enter number"))
#for i in range(0,num):

d = []
f,g = "Fname","Lname"
d.append(f)
d.append(g)

a = input("Enter name")
gg = a.title()
b=gg.split(" ")
print(b)
d=dict(zip(d,b))
print(d)

mark = []
for i in range(0,3):
    while True:
        c = int(input("enter marks: "))
        if c>=0 and c<=100:
            marks=c
            mark.append(marks)
            break
print(mark)
marks1,marks2,marks3=mark[0],mark[1],mark[2]
print(marks1,marks2,marks3)



Enter namevipendra pal
['Vipendra', 'Pal']
{'Fname': 'Vipendra', 'Lname': 'Pal'}
enter marks: 44
enter marks: 55
enter marks: 66
[44, 55, 66]
44 55 66


In [15]:
# Find square and sum 

a=[1,2,3,4,5,6,7,8,9,10]
print(sum(a))

print('\n')

for i in range(10):
    if i<10:
        i=i*i
        print(i)

55


0
1
4
9
16
25
36
49
64
81


In [17]:
students = dict()
n = int(input("how many records you want to enter"))
for i in range(n):
    sname = input("enter name")
    marks= []
    for j in range(5):
        m = float(input("enter marks {}".format(i)))
        marks.append(m)
        ss = sum(marks)
    print("total marks",ss)
    print('\n')
    students[sname] = marks
    
print(students)

how many records you want to enter2
enter nameVipen
enter marks 055
enter marks 066
enter marks 077
enter marks 033
enter marks 022
total marks 253.0


enter nameajay
enter marks 189
enter marks 178
enter marks 188
enter marks 166
enter marks 155
total marks 376.0


{'Vipen': [55.0, 66.0, 77.0, 33.0, 22.0], 'ajay': [89.0, 78.0, 88.0, 66.0, 55.0]}


In [18]:
# if you do not know how many arguments will be passed in your function
# add a * befor parameter in function

def my_function(*kids):
    print("thr",kids[2])
    print("thr"+kids[2])
    print("thr",kids)
my_function("email","jab","hav")

thr hav
thrhav
thr ('email', 'jab', 'hav')


In [19]:
# we difine values in  function so it not change its index

def my_function(child3,child2,child1):
    print("thr",child3)
    print("thr",child2)
my_function(child1 = "email",child2 = "jab",child3 = "hav")

thr hav
thr jab


In [20]:
def my_function(country):
    print("i am from : "+country)
my_function("swedan")
my_function("india")
my_function("time")
my_function("Brazil")

i am from : swedan
i am from : india
i am from : time
i am from : Brazil


In [21]:
def my_function(country = "Norway"):
    print("i am from : "+country)
my_function("swedan")
my_function("india")
my_function()
my_function("Brazil")

i am from : swedan
i am from : india
i am from : Norway
i am from : Brazil


In [22]:
def my_function(food):
    for x in food:
        print(x)
fruits = ["app","bana","cherr"]

my_function(fruits)

app
bana
cherr


In [23]:
def my_function(x):
        return 5 * x

a=my_function(3)
print(a)
print(my_function(3))
print(my_function(4))
print(my_function(5))

15
15
20
25


In [24]:
# Using Function

students = dict()

def st_name():
    return input("Enter name")
    
def st_marks():
    marks = []
    for j in range(5):
        m = float(input("enter marks {}".format(i)))
        marks.append(m)
        ss = sum(marks)
    print("total marks",ss)
    print('\n')
    students[sname] = marks

    
n = int(input("how many records you want to enter"))
for i in range(n):
    sname = st_name()
    st_marks()
print(students)

how many records you want to enter2
Enter namevipen
enter marks 067
enter marks 044
enter marks 033
enter marks 022
enter marks 011
total marks 177.0


Enter nameAjay
enter marks 165
enter marks 133
enter marks 177
enter marks 199
enter marks 167
total marks 341.0


{'vipen': [67.0, 44.0, 33.0, 22.0, 11.0], 'Ajay': [65.0, 33.0, 77.0, 99.0, 67.0]}


In [25]:
# Python lambda
# A lambda is small anyonms function
# a lambda function can take any number of arguments and only have only one expression

x = lambda a: a+10
print(x(5))

15


In [26]:
x = lambda a, b: a*b
print(x(5,6))

30


In [27]:
# In python we generally use it as an a higher order function
# it uses with map(), filter(), reduce()

my_list = [1,5,4,9,8,12,15,18]
new_list = list(filter(lambda x: (x%2==0), my_list))
print(new_list)

[4, 8, 12, 18]


In [28]:
# Find age above 30 years
ages = [56,45,34,36,23,56,18]
new_ages = list(filter(lambda x: x>30, ages))
print(new_ages)

[56, 45, 34, 36, 56]


In [29]:
# map()

my_list = [1,5,4,9,8,12,15,18]
new_list = list(map(lambda x: x*2, my_list))
print(new_list)

[2, 10, 8, 18, 16, 24, 30, 36]


In [30]:
# Convert in upper case
animals = ["dog","cat","parrot","rabbit"]
u_animals = list(map(lambda a: str.upper(a), animals))

print(u_animals)

['DOG', 'CAT', 'PARROT', 'RABBIT']


In [31]:
from functools import reduce


seq = [1,2,3,4,5]
fil_res = reduce (lambda x,y : (x*y), seq)
print(fil_res)

120


In [32]:
from functools import reduce
seq = [1,2,3,4,5]
l = len(seq)
fil_res = reduce (lambda x,y : x+y, seq)
a = fil_res/l
print(a)

3.0


## Numpy Array

In [33]:
import numpy as np

In [34]:
# input array

arr = np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [35]:
# 1-D Array

arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [36]:
# 2-D Array 

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [37]:
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [38]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])

2


In [39]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,-1])

5


In [40]:
# Slicing

arr = np.array([1,2,3,4,5])
print(arr[1:3])

[2 3]


In [41]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[4,3,5,6,7]])
print(arr[-1,-4])

3


In [42]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:3])
print(arr[:4])
print(arr[4:])
print(arr[1:6:2])
print(arr[::2])

[2 3]
[1 2 3 4]
[5 6 7 8]
[2 4 6]
[1 3 5 7]


In [43]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:6:2])

[2 4 6]


In [44]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
print(arr[::2])
print(arr[1::2])

[ 0  2  4  6  8 10]
[ 1  3  5  7  9 11]


In [45]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
arr.shape

[7 8 9]


(2, 5)

In [46]:
print(arr[:2,3])

[4 9]


In [47]:
arr = np.array([1,2,3,4,5,6,7,8])
x=arr.copy()
x[0]=40
print(arr)

print(x)
arr.shape

[1 2 3 4 5 6 7 8]
[40  2  3  4  5  6  7  8]


(8,)

In [48]:
a = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(a)
print('\n')
print(a[:,1:2])

[[11 22 33]
 [44 55 66]
 [77 88 99]]


[[22]
 [55]
 [88]]


In [49]:
a = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(a)
print('\n')
print(a[1::2,::2])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


[[15 21]
 [39 45]]


In [50]:
ar = np.array([[1,2,3],[4,5,6]])
for x in ar:
    print(x)

[1 2 3]
[4 5 6]


In [51]:
for x in ar:
    for y in x:
        print(y)

1
2
3
4
5
6


***

<center> <font color='Red' size=5>For more practice i have uploaded another file Practice and solution set.</font></center>

<center> <font color='blue' size=5>See you in next ipynb file</font></center>

** *