<img src = "Logo1.png" width=40%></img>

***

## <center> Python Sessions : </center>

<br>


Zoom Meeting link

https://zoom.us/j/95762064687?pwd=QkRiWXE4NFNmUWlEeDBFQlFNbEpuZz09



#### Meeting ID: 957 6206 4687
#### Passcode: 665892

***

### <center> Date : 05 Jan 2021 </center>

***

In [1]:
#casting 
# if you want to specify the data type variable this can be done by casting

x=3
print(type(x)) #check datatype
x=str(3)
print(type(x))


<class 'int'>
<class 'str'>


In [2]:
# case sensitive or latest value put

a=10
A=5
A=7
print(a)
print(A)
print(A)

10
7
7


In [3]:
#camel case 
# each word except the first start with capital letter

myVariableName = "John"

# Pascal case
# each word start with capital letter

MyVariableName = "John"

#snake case
#each word is seprate by underscore
my_variable_name = "John"

What is XYZ by default

In [4]:
# Pyhton  variable : assign multiple variable

x,y,z = "Orange", "Banana", "Cherry"
xyz = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)
print(xyz)

Orange
Banana
Cherry
('Orange', 'Banana', 'Cherry')


In [5]:
# Output variable
#The python print statement is often used to output variable

# to create both text and a variable python use the + charactor

x = "awasome"
y=3
y=str(3)

print("pythn is"+x)
print("pythn is"+y)
print("pythn is"+str(y))
print("pythn is",3)


pythn isawasome
pythn is3
pythn is3
pythn is 3


In [6]:
# taking input from user

a= int(input("enter number first"))
print(a)
b= int(input("enter number second"))
print(b)
c=a+b
print(c)
print(type(c))

enter number first66
66
enter number second98
98
164
<class 'int'>


In [7]:
# wheather an number is +VE or -VE or Zero

x=int(input("Enter number")) #take input from user
if x<0:                      #apply conditions
    print("-ve")
elif x>0:
    print("+ve")
else:
    print("Zero")

Enter number-76
-ve


In [8]:
# wheather number is odd or even

x = int(input("Enter number"))

if x%2 == 0:          # check reminder 
    print("even")
else:
    print("odd")

Enter number-89
odd


In [10]:
# Check number range between 0 to 100 and take 5 input from user and gave grade

while True:
    a = int(input("Enter 1st subject marks: "))
    if 100>= a >= 0:
        print(a)
        break

while True:
    b = int(input("Enter 2nd subject marks: "))
    if 100>= b >= 0:
        print(b)
        break

while True:
    c = int(input("Enter 3rd subject marks: "))
    if 100>= c >= 0:
        print(c)
        break
    
while True:
    d = int(input("Enter 4th subject marks: "))
    if 100>= d >= 0:
        print(d)
        break
while True:
    e = int(input("Enter 5th subject marks: "))
    if 100>= e >= 0:
        print(e)
        break
        
num = ((a+b+c+d+e)/500)*100          #Restore values and find percentage
print(num)
if num <80:
    print("D")
elif num>=95:
    print("A")
elif num>=88:
    print("B")
elif num>=80:
    print("C")

Enter 1st subject marks: 99
99
Enter 2nd subject marks: 98
98
Enter 3rd subject marks: 97
97
Enter 4th subject marks: 99
99
Enter 5th subject marks: 99
99
98.4
A


### <center> Practice Set </center>

In [11]:
# Python program to find the maxmium number 

a = int(input("Enter first number"))   # Take input from user
b = int(input("Enter second number"))
c = int(input("Enter third number"))

if (a >= b) and (a >= c):
    l = a
elif (b >= a) and (b >= c):
    l = b
else:
    l = c

print("The max is", l)

Enter first number5
Enter second number-8
Enter third number2
The max is 5


In [12]:
# Python Program to print Prime Numbers from 1 to 50
 
for Number in range (1, 51):
    count = 0
    for i in range(2, (Number//2 + 1)):
        if(Number % i == 0):
            count = count + 1
            break

    if (count == 0 and Number != 1):
        print(" %d" %Number, end = '  ')

 2   3   5   7   11   13   17   19   23   29   31   37   41   43   47  

In [13]:
#Assign value for variables

a,b = 4,5
print(a,b) #print values
a,b = b,a #swap values 
print(a,b)#print after swaping

4 5
5 4


In [14]:
#swap number without using temp or third variable

a = 8
b = 7
a = a + b
b = a - b
a = a - b
print(a,b)

7 8


In [15]:
# Check validation of mobile number that start with 6,7,8,9
N = int(input("enter number : "))
b= str(N) #convert in string
if len(b)==10: #check length of given input if it is 10 then only show valid else unvalid
    if b[0] == "9" or b[0] == "8" or b[0] == "7" or b[0] == "6": #Check for given numbers
        print("valid")
    else:
        print("UV")
else:
    print("UV")

enter number : 9782035434
valid


***

## <center> Date : 06 Jan 2021 </center>

***

In [16]:
# Python Identity operator
# Identity operator are used to compare the object

x = ["apple", "banaba"]
y = ["apple", "banaba"]
z = x
print(x is z)

#return true because it has same object

print(x is y)
# different object

print(x == y)
# compare return true because it equal to y

True
False
True


In [17]:
# Python membership operator
# membership operator used to test sequence is present in an object : in , not in
x = ["apple", "banana"]

print("kiwi" not in x)
print("kiwi" in x)

True
False


In [18]:
# calculate string length

a = "hello , world!"
c=0
for x in a:
    c+=1
print(c)

14


In [19]:
# Count an specific word how much times it comes

a="hello my name is xyz, my age is xyz, i work for xyz"
c=0
for x in a:
    if x is "xyz":
        c+=1
print(c)

0


In [20]:
#swap first and last charactor of string using slicing

a=input("Enter : ")
print(a[-1]+a[1:-1]+a[0])

Enter : Hello world!
!ello worldH


In [21]:
# Replace space using special charactor

a = input("Enter : ")
a = a.replace(' ','@')
print(a)

Enter : Vipendra pal Rajput
Vipendra@pal@Rajput


In [22]:
# Count charactor and word 

a = input("Enter : ")
c=0
d=0
for x in a:
    c+=1
    if x == " ":
        d+=1
print(d+1)
print(c)

Enter : hello world i am vipen
5
22


In [23]:
#count charactor and digit with lower and upper

s="helloWORLD45"
c=0
d=0
t=0    
for x in s: 
    if x>='a'and x<='z': 
        c+=1                 
    if x>='A'and x<='Z': 
        d+=1
    if x>='0' and x<='9':
        t+=1
print(c) 
print(d)     
print(t)

5
5
2


In [24]:
#Reverse string using slicing

a="hell0 world"
a[::-1]

'dlrow 0lleh'

### <center> Practice Set </center>

In [25]:
# Palindrom using slicing

a=input("Enter String for check palindrome: ")
print(a)
b = a[::-1]
print(b)
if a==b:
    print(True)
else:
    print(False)

Enter String for check palindrome: MAMA
MAMA
AMAM
False


In [26]:
# Remove Special charactor from string
a = [";", "!", "*", "@","_","!","#","$","%","^","&","*","(",")","<",">","?","/","|","}","{","~",":","[","]"] 
b = input("Enter : ")
print (b) 
for x in a : 
    b = b.replace(x, '') 
print(b) 

Enter : vip!@#$%ndr(){[a
vip!@#$%ndr(){[a
vipndra


In [27]:
def s(a):
    x = (c for c in a if 47 < ord(c) <58 or 64 < ord(c) < 91 or 97 < ord(c) < 122 or ord(c)==32)
    print(''.join(x))

t = input("ENTER")
print(s(t))

ENTERvupe9827 dkjgdKJ44
vupe9827 dkjgdKJ44
None


In [28]:
# Find the median of given string

a=[1,2,3,4,5,6,7,8,9,10]
n=len(a)
if n%2 == 0:
    m = n//2
    print((a[m]+a[m-1])/2)
else:
    m = n//2
    print(a[m])
    

5.5


In [29]:
# Check how many time an input letter occour in the given string

bag = "avvGDJag"
fav = input("Enter String :")
c=0
for i in bag:
    if i in fav:
        c+=1
print(c)

Enter String :vipendra
4


In [30]:
b = [7,1,5,3,6,9]
l=len(b)
a=[]
for i in range(1,l):
    if b[i]>b[i-1]:
        mx = b[i]-b[i-1]
        a.append(mx)
        print(sum(a))

4
7
10


***

## <center> Date : 07 Jan 2021 </center>

***

In [31]:
# Count number of elemnets in list
a = ["apple","banana", "cherry"]
c=0
for x in a:
    c+=1
print(c)

3


In [32]:
name = []    # take empty list
age = []
clas=[]
grade=[]
num = int(input("Enter How many students data you want to enter")) # take input from user 
for i in range(0,num): #In range of input
    while True:
        a = input("enter name : ")
        if a.isalpha() == True:
            #print(a)
            name.append(a)
            break
    while True:
        b = int(input("enter Age : "))
        if b>=20 and b<=40:
            #print(b)
            age.append(b)
            break

    while True:
        c = int(input("Grade : "))
        if c>=0 and c<=9:
            #print(c)
            grade.append(c)
            break
    while True:
        d = input("enter Class : ")
        e =len(d)
        if e ==4:
            d.isalnum()
            #print(d)
            clas.append(d)
            break
        

listss = name+age+grade+clas
print(listss)

for i in range(0,num):
    listt = "my name is {} and my age is {} and i get {} grade in class {}".format(name[i],age[i],grade[i],clas[i])
    print(listt)

Enter How many students data you want to enter2
enter name : vipen
enter Age : 22
Grade : 9
enter Class : IT94
enter name : Arjun
enter Age : 23
Grade : 8
enter Class : CS04
['vipen', 'Arjun', 22, 23, 9, 8, 'IT94', 'CS04']
my name is vipen and my age is 22 and i get 9 grade in class IT94
my name is Arjun and my age is 23 and i get 8 grade in class CS04


In [33]:
# Programme for bubble sort

a = [10,50,30,40,5]
b=len(a)
for i in range(0,b):
    for j in range(0,b-1):
        if(a[j] > a[j+1]):
            temp = a[j]
            a[j] = a[j+1]
            a[j+1] = temp
print(a)

[5, 10, 30, 40, 50]


In [34]:
#packing 
my_tuple = 3.6, "dog", 4
print(my_tuple)
#unpacking
a,b,c = my_tuple
print(a)
print(b)
print(c)

(3.6, 'dog', 4)
3.6
dog
4


In [35]:
#single variable is not tuple
a= 2
print(a)
#make single value tuple
m=("hello",)
print(m)
m = "hello",
print(m)

2
('hello',)
('hello',)


### <center> Practice Set </center>

#### Q1. Python Program to Read a List of Words and Return the Length of the Longest One
#### Q2. Given a Python list, find value 20 in the list, and if it is present, replace it with 200. Only update the first occurrence of a value
#### Access value 20 from the following tuple
#### aTuple = ("Orange", [10, 20, 30], (5, 15, 25))

#### Q4. Counts the number of occurrences of item 50 from a tuple
####  tuple1 = (50, 10, 60, 70, 50)


In [36]:
# Python Program to Read a List of Words and Return the Length of the Longest One

a = ["apple" , "banana", "man", "guavava"]
l = [len(i) for i in a]
print(l)
ml = max(l) 
print(ml) 

[5, 6, 3, 7]
7


In [37]:
#Given a Python list, find value 20 in the list, and if it is present, replace it with 200. Only update the first occurrence of a value

l = [5, 15, 25,20,50,30,40,20,10]
print(l)
i = l.index(20)  #checking index of 20
l[i] = 200
print(l)

[5, 15, 25, 20, 50, 30, 40, 20, 10]
[5, 15, 25, 200, 50, 30, 40, 20, 10]


In [38]:
# Access value 20 from the following tuple

aTuple = ("Orange", [10, 20, 30], (5, 15, 25))
aTuple[1][1]

20

In [39]:
# Counts the number of occurrences of item 50 from a tuple

tuple1 = (50, 10, 60, 70, 50)
c=0
for x in tuple1:
    if x==50:
        c+=1
print(c)

2


In [40]:
# insert element in list

def s(idx,el,lst):
    print(lst)
    lst1 = lst[:idx]
    lst1.append(el)
    lst1 +=lst[idx:]
    print(lst1)

idx=int(input("enter index"))
el=input("enter element")
lst=["vip","end","ra","pal"]
s(idx,el,lst)

enter index3
enter elementHive
['vip', 'end', 'ra', 'pal']
['vip', 'end', 'ra', 'Hive', 'pal']


In [41]:
#append list in another list

def s1(l,t):
    print(l[:]+[t])
l=["apple","banana"]
t=["SEEk","ACE","cherry","6"]
s1(l,t)

['apple', 'banana', ['SEEk', 'ACE', 'cherry', '6']]


In [42]:
# Extend another list

def s1(l,t):
    print(l[:]+t[:])
l=["apple","banana"]
t=["SEEk","ACE","cherry","6"]
s1(l,t)

['apple', 'banana', 'SEEk', 'ACE', 'cherry', '6']


In [43]:
# check length of the string without direct len function

a = ["apple","banana","mango","charry"]
c =0
while c!=len(a):
    c+=1
print(c)

4


In [44]:
# take input & check minimum input 5
def s():
    while True:
        a=input("enter string :") # take input from user
        b=a.split(" ")   #break string when we found space in string
        print(b)
        if len(b)>=5:
            break
s()

enter string :i am vipendra pal rajput
['i', 'am', 'vipendra', 'pal', 'rajput']


In [45]:
# take input & check minimum input 5 and nubering index on which number
def s():
    while True:
        a=input("enter string :") # take input from user
        b=a.split(" ")   #break string when we found space in string
        print(b)
        if len(b)>=5:
            for i in range(0,len(b)):
                print(i+1,b[i])  # print index and elements
            break
s()

enter string :i am vipen
['i', 'am', 'vipen']
enter string :i am vipendra pal rajput
['i', 'am', 'vipendra', 'pal', 'rajput']
1 i
2 am
3 vipendra
4 pal
5 rajput


In [46]:
# take input & check minimum input 5 and nubering index
def s():
    while True:
        a=input("enter string :") # take input from user
        b=a.split(" ")   #break string when we found space in string
        print(b)
        if len(b)>=5:
            for i in range(0,len(b)):
                print(i+1,len(b[i]),b[i])    # print index and elements
            break
s()

enter string :hello my name is vipendra
['hello', 'my', 'name', 'is', 'vipendra']
1 5 hello
2 2 my
3 4 name
4 2 is
5 8 vipendra


In [47]:
users = ["abc","def","ghi","jkl"]
choice = ["1","2","3","4"]
for i in range(0,len(users)):
    t = "name of user is {} and have index {}".format(users[i],choice[i])
    print(t)

name of user is abc and have index 1
name of user is def and have index 2
name of user is ghi and have index 3
name of user is jkl and have index 4


In [48]:
users = ["abc","def","ghi","jkl"]
choice = ["1","2","3","4"]
for i in range(0,len(users)):
    t = "name of user is {1} and have index {0}".format(users[i],choice[i])
    print(t)

name of user is 1 and have index abc
name of user is 2 and have index def
name of user is 3 and have index ghi
name of user is 4 and have index jkl


***

## <center> Date : 08 Jan 2021 </center>

***

#### Sets {}

In [1]:
# a set is unordered or unindexed

a = {"a","b","c","d"}
print(a)

{'d', 'c', 'b', 'a'}


In [2]:
# set do not allow duplicate values

a={"a","b","a","d","e","r","d"}
print(a)
a.add("vip")
for x in a:
    print(a)

{'b', 'a', 'd', 'r', 'e'}
{'b', 'a', 'vip', 'd', 'r', 'e'}
{'b', 'a', 'vip', 'd', 'r', 'e'}
{'b', 'a', 'vip', 'd', 'r', 'e'}
{'b', 'a', 'vip', 'd', 'r', 'e'}
{'b', 'a', 'vip', 'd', 'r', 'e'}
{'b', 'a', 'vip', 'd', 'r', 'e'}


In [3]:
# apply union function to merge to sets but they arrenge in unordered format

set = {"a","b","c","d"}
set1={1,2,3}
set3 = set.union(set1)
print(set3)
print('\n')
# to remove repetated values from set we use intersection

set = {"a","b","c","d"}
set1={1,2,3,'a'}
set3 = set.union(set1)-set.intersection(set1)
print(set3)

print('\n')

# Print that is comman value in two sets

s={1,2,3,4,5}
s1={5,6,7,1,2}
print(s1.intersection(s))

{1, 2, 'c', 3, 'b', 'a', 'd'}


{1, 2, 3, 'b', 'd', 'c'}


{1, 2, 5}


In [1]:
# Count vowels on the bases of set

s=input("Please enter : ");
d=set("aeiouAEIOU")
c=0
for i in s:
    if i in d:
           c+=1;    
print(c)

Please enter : vipendraVIPENDRA
6


In [2]:
# Print that is not comman value in two sets

s={1,2,3,4,5}
s1={5,6,7,1,2}
s3 = set()
for i in s:
    if i not in s1:
        s3.add(i)
for i in s1:
    if i not in s:
        s3.add(i)
    
print(s3) 

{3, 4, 6, 7}


### Dictionary


In [3]:
# Print dictionary 

the = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
}
print(the)

{'brand': 'Ford', 'model': 'mustang', 'Year': 1999}


In [4]:
# Print dictionary value on the bases of keys

the = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
}
print(the["Year"])


# if we enter duplicate value in list then it take latest value by default

the = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
    "Year":1988
}
print(the)
print(the["Year"])


# Dictionary contains all string int boolean and list inside dict

the = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
    "elc":True,
    "Year":1988,
    "colors":["red","blac"]
}
print(the)

1999
{'brand': 'Ford', 'model': 'mustang', 'Year': 1988}
1988
{'brand': 'Ford', 'model': 'mustang', 'Year': 1988, 'elc': True, 'colors': ['red', 'blac']}


In [5]:
# Updeting keys
car = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
    "Year":1988
}
x=car.keys()
y=car.values()

print(x)
print(y)
car["color"]="white"

x=car.keys()
y=car.values()

print(x)
print(y)


dict_keys(['brand', 'model', 'Year'])
dict_values(['Ford', 'mustang', 1988])
dict_keys(['brand', 'model', 'Year', 'color'])
dict_values(['Ford', 'mustang', 1988, 'white'])


In [6]:
# access items
# Updeting keys
car = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
    "Year":1988
}
x=car.items()

print(x)
car["Year"]=2020

print(x)

dict_items([('brand', 'Ford'), ('model', 'mustang'), ('Year', 1988)])
dict_items([('brand', 'Ford'), ('model', 'mustang'), ('Year', 2020)])


In [7]:
for x in car:
    print(x)
    
print('\n')

for x in car:
    print(car[x])
    
    
print('\n')

for x in car:
    print(x,car[x])
    
print('\n')

for x in car.items():
    print(x)
    
print('/n')

for x,y in car.items():
    print(x,y)

brand
model
Year


Ford
mustang
2020


brand Ford
model mustang
Year 2020


('brand', 'Ford')
('model', 'mustang')
('Year', 2020)
/n
brand Ford
model mustang
Year 2020


In [8]:
car = {
    "brand":"Ford",
    "model":"mustang",
    "Year":1999,
    "Year":1988
}
mycar = car.copy()
print(mycar)

{'brand': 'Ford', 'model': 'mustang', 'Year': 1988}


In [9]:
myfam = {
    "child":{
        "name":"Email",
        "year":2004
    },
    "child1":{
        "name":"tobias",
        "year":2006
    },
    "child2":{
        "name":"tins",
        "year":2011
    },
}


print(myfam)
print("\n")
print(myfam.values())
print("\n")

print(myfam.keys())
print("\n")

print(myfam.items())

{'child': {'name': 'Email', 'year': 2004}, 'child1': {'name': 'tobias', 'year': 2006}, 'child2': {'name': 'tins', 'year': 2011}}


dict_values([{'name': 'Email', 'year': 2004}, {'name': 'tobias', 'year': 2006}, {'name': 'tins', 'year': 2011}])


dict_keys(['child', 'child1', 'child2'])


dict_items([('child', {'name': 'Email', 'year': 2004}), ('child1', {'name': 'tobias', 'year': 2006}), ('child2', {'name': 'tins', 'year': 2011})])


In [10]:
child = {
    "name":"Email",
    "year":2004
}
child1= {
    "name":"tobias",
    "year":2006
}
child2 = {
    "name":"tins",
    "year":2011
}
myfam={
    "c1" :child,
    "c2":child1,
    "c3": child2
}


print(myfam)
print("\n")


{'c1': {'name': 'Email', 'year': 2004}, 'c2': {'name': 'tobias', 'year': 2006}, 'c3': {'name': 'tins', 'year': 2011}}




In [11]:
# take input and pair them as the key and values

key = input("enyter added")
value = input("enter grade  value")
d={}
d.update({key:value})
print(d)

enyter addedvipen 9
enter grade  value9
{'vipen 9': '9'}


In [12]:
# take input from user to enter in dictionary key and values

num = int(input("enter how many entry you want to enter"))
d={}
for i in range(0,num):
    key = input("enyter keys : ")
    value = input("enter values : ")
    d.update({key:value})
    print(d)

enter how many entry you want to enter2
enyter keys : vipen1
enter values : 94
{'vipen1': '94'}
enyter keys : vipen2
enter values : 90
{'vipen1': '94', 'vipen2': '90'}


In [13]:
# Merge to dictionay on the bases of key & value pairs
x=["a","b","c"]
v=[1,2,3]
d=dict(zip(x,v))
print(d)

{'a': 1, 'b': 2, 'c': 3}


### <center> Practice Set </center>

#### Question
    student name=[Alice, John, Bob]
    Grade=[8,7,10]
    Q Give name of student scoring higest marks with his marks
    Bob-10

       Convert inito dictionary thn do it again


2. Q o Sum All the values  in a Dictionary
    1: 100
    2:200
    3:500


3. Q. Merge two dictionaries into 1

4. Q. Get the key corresponding to the minimum value from the following dictionary
    Sub 1: 6
    Sub 2: 7
    Sub 3: 5


In [2]:
s = ["alice", "john","trum", "BOB","Race","TUR"]
grade = [8,7,9,16,11,16]
l = max(grade)
for i in range(len(s)):
    if grade[i] ==l:
            print(s[i],grade[i])

BOB 16
TUR 16


In [3]:
s = ["alice", "john","trum", "BOB","Race","TUR"]
grade = [8,7,9,16,11,16]
dt=dict(zip(s,grade))
print(dt)
m = max(dt.values())
print(m)
for i in dt:
    if i==m:
        print()

{'alice': 8, 'john': 7, 'trum': 9, 'BOB': 16, 'Race': 11, 'TUR': 16}
16


In [4]:
# Find Sum of All the values  in a Dictionary

dict = {"a": 60, "b":150, "c":200,"d":120}
s = 0
for i in dict:
    s = s + dict[i] 
print(s)
    

530


In [5]:
# Merge two dictionaries into one

f1 = {'a': 'apple', 'b': 'Banana' , 'o': 'Orange'}
f2 = { 'k': 'Kiwi', 'm': 'Mango','o': 'fruits'}
f1.update(f2)
print(f1)

{'a': 'apple', 'b': 'Banana', 'o': 'fruits', 'k': 'Kiwi', 'm': 'Mango'}


In [6]:
# Get the key corresponding to the minimum value from the following dictionary


a = {'Sub 1':6, 'Sub 2':7, 'Sub 3':5}
print(a.values())
value = min(a.values())
print(value)
for i in a: 
    if a[i] == value:
        print(i,a[i])

dict_values([6, 7, 5])
5
Sub 3 5


In [1]:
# Enter Name and last name and capital first letter and enter marks and grade

#num = int(input("enter number"))
#for i in range(0,num):

d = []
f,g = "Fname","Lname"
d.append(f)
d.append(g)

a = input("Enter name")
gg = a.title()
b=gg.split(" ")
print(b)
d=dict(zip(d,b))
print(d)

mark = []
for i in range(0,3):
    while True:
        c = int(input("enter marks: "))
        if c>=0 and c<=100:
            marks=c
            mark.append(marks)
            break
print(mark)
marks1,marks2,marks3=mark[0],mark[1],mark[2]
print(marks1,marks2,marks3)



Enter namevipen pal
['Vipen', 'Pal']
{'Fname': 'Vipen', 'Lname': 'Pal'}
enter marks: 3
enter marks: 4
enter marks: 5
[3, 4, 5]
3 4 5


In [2]:
# Find square and sum 

a=[1,2,3,4,5,6,7,8,9,10]
print(sum(a))

print('\n')

for i in range(10):
    if i<10:
        i=i*i
        print(i)

55


0
1
4
9
16
25
36
49
64
81


***

## <center> Date : 11 Jan 2021 </center>

***

In [28]:
students = dict()
n = int(input("how many records you want to enter"))
for i in range(n):
    sname = input("enter name")
    marks= []
    for j in range(5):
        m = float(input("enter marks {}".format(i)))
        marks.append(m)
        ss = sum(marks)
        print("total marks",ss)
    print('\n')
    students[sname] = marks
    
print(students)

how many records you want to enter1
enter namevipen
enter marks 02
total marks 2.0
enter marks 05
total marks 7.0
enter marks 06
total marks 13.0
enter marks 07
total marks 20.0
enter marks 08
total marks 28.0


{'vipen': [2.0, 5.0, 6.0, 7.0, 8.0]}


In [32]:
# if you do not know how many arguments will be passed in your function
# add a * befor parameter in function

def my_function(*kids):
    print("thr",kids[2])
    print("thr"+kids[2])
    print("thr",kids)
my_function("email","jab","hav")

thr hav
thrhav
thr ('email', 'jab', 'hav')


In [35]:
# we difine values in  function so it not change its index

def my_function(child3,child2,child1):
    print("thr",child3)
    print("thr",child2)
my_function(child1 = "email",child2 = "jab",child3 = "hav")

thr hav
thr jab


In [41]:
def my_function(country):
    print("i am from : "+country)
my_function("swedan")
my_function("india")
my_function("time")
my_function("Brazil")

i am from : swedan
i am from : india
i am from : time
i am from : Brazil


In [40]:
def my_function(country = "Norway"):
    print("i am from : "+country)
my_function("swedan")
my_function("india")
my_function()
my_function("Brazil")

i am from : swedan
i am from : india
i am from : Norway
i am from : Brazil


In [42]:
def my_function(food):
    for x in food:
        print(x)
fruits = ["app","bana","cherr"]

my_function(fruits)

app
bana
cherr


In [46]:
def my_function(x):
        return 5 * x

a=my_function(3)
print(a)
print(my_function(3))
print(my_function(4))
print(my_function(5))

15
15
20
25


In [50]:
students = dict()

def st_name():
    return input("Enter name")
    
def st_marks():
    marks = []
    for j in range(5):
        m = float(input("enter marks {}".format(i)))
        marks.append(m)
        ss = sum(marks)
        print("total marks",ss)
    print('\n')
    students[sname] = marks

    
n = int(input("how many records you want to enter"))
for i in range(n):
    sname = st_name()
    st_marks()
print(students)

how many records you want to enter1
Enter namevip
enter marks 03
total marks 3.0
enter marks 04
total marks 7.0
enter marks 05
total marks 12.0
enter marks 06
total marks 18.0
enter marks 07
total marks 25.0


{'vip': [3.0, 4.0, 5.0, 6.0, 7.0]}


In [2]:
students = dict()

def st_name():
    return input("Enter name")
    
def st_marks():
    marks = []
    for j in range(5):
        m = float(input("enter marks {}".format(i)))
        marks.append(m)
        ss = sum(marks)
        sss = (ss*100)/500
    print("avg" ,sss)
    print("total marks",ss)
    
    print('\n')
    students[sname] = marks
    
  
n = int(input("how many records you want to enter"))
for i in range(n):
    sname = st_name()
    st_marks()
    ssss = (sss/n)
    print(ssss)
print(students)

how many records you want to enter2
Enter namevip
enter marks 03
enter marks 04
enter marks 05
enter marks 06
enter marks 07
avg 5.0
total marks 25.0




NameError: name 'sss' is not defined

In [63]:
# Python lambda
# A lambda is small anyonms function
# a lambda function can take any number of arguments and only have only one expression

x = lambda a: a+10
print(x(5))

15


In [64]:
x = lambda a, b: a*b
print(x(5,6))

30


In [65]:
# In python we generally use it as an a higher order function
# it uses with map(), filter(), reduce()

my_list = [1,5,4,9,8,12,15,18]
new_list = list(filter(lambda x: (x%2==0), my_list))
print(new_list)

[4, 8, 12, 18]


In [67]:
# Find age above 30 years
ages = [56,45,34,36,23,56,18]
new_ages = list(filter(lambda x: x>30, ages))
print(new_ages)

[56, 45, 34, 36, 56]


In [69]:
# map()

my_list = [1,5,4,9,8,12,15,18]
new_list = list(map(lambda x: x*2, my_list))
print(new_list)

[2, 10, 8, 18, 16, 24, 30, 36]


In [71]:
# Convert in upper case
animals = ["dog","cat","parrot","rabbit"]
u_animals = list(map(lambda a: str.upper(a), animals))

print(u_animals)

['DOG', 'CAT', 'PARROT', 'RABBIT']


In [78]:
from functools import reduce


seq = [1,2,3,4,5]
fil_res = reduce (lambda x,y : (x*y), seq)
print(fil_res)

120


In [81]:
from functools import reduce
seq = [1,2,3,4,5]
l = len(seq)
fil_res = reduce (lambda x,y : x+y, seq)
a = fil_res/l
print(a)

3.0


### <center> Practice Set </center>

###### Q1.Create a function showEmployee() in such a way that it should accept employee name, and it’s salary and display both, and if the salary is missing in function call it should show it as 9000
###### Q2. Return the mean and median of the given list
######  Q3. Make a menu driven calculator using functions.
    Enter 1 to perform addition
    Enter 7 to exit
    

In [162]:
# Create a function showEmployee() in such a way that it should accept employee name, 
# and it’s salary and display both, and if the salary is missing in function call it should show it as 9000

def showEmployee(a,b = 9000):
    print("Emp_name is : ", a, "salary is:", b)

showEmployee("Vipenn",5)
showEmployee("Vipen",)

Emp_name is :  Vipenn salary is: 5
Emp_name is :  Vipen salary is: 9000


In [2]:
# find meadian 

def median(list):
    list.sort()
    l = len(list)
    mid = (l-1)//2
    if(l%2==0):
        return (list[mid] + list[mid+1])/2
    else:
        return list[mid]
        
list1 = [2, 3, 3, 5, 6, 7, 7]
list2 = [3, 4, 6, 6, 7, 8, 8, 10]
print("Median : ", median(list1))
print("Median : ", median(list2))

Median :  5
Median :  6.5


In [8]:
# Make a menu driven calculator using functions.
# Enter 1 to perform addition & Enter 7 to exit

def add(n1,n2):
    return n1 + n2
def sub(n1,n2):
    return n1 - n2
def mul(n1,n2):
    return n1 * n2
def div(n1,n2):
    if n2 ==0:
        return 'invalid divisiual : division can not be zero'
    return n1 / n2

print("Enter Number For performing operation \n" "1. Addition \n" "2. Subtraction\n" "3. Multiplication \n""4. Division \n" "7. Exit \n")

s = int(input("what operation do you want to do ?  "))

if s>0 and s<5:
    print("Enter two numbers")
    num1 = int(input("Enter Nuber 1st : "))
    num2 = int(input("Enter Number 2nd : "))
    if s==1:
        print("Addition is : ",add(num1,num2))
    elif s==2:
        print("Subtraction is : ",sub(num1,num2))
    elif s==3:
        print("Multiplation is : ",mul(num1,num2))
    else:
        print("Division is : ",div(num1,num2))
elif s==7:
    pass 
else:
    print("Invalid")



Enter Number For performing operation 
1. Addition 
2. Subtraction
3. Multiplication 
4. Division 
7. Exit 

what operation do you want to do ?  4
Enter two numbers
Enter Nuber 1st : 1
Enter Number 2nd : 0
Division is :  invalid divisiual : division can not be zero


***

## <center> Date : 12 Jan 2021 </center>

***

## Numpy Array

In [1]:
import numpy as np

In [98]:
# input array

arr = np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [99]:
# 1-D Array

arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [102]:
# 2-D Array 

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [103]:
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [108]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])

2


In [109]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,-1])

5


In [110]:
# Slicing

arr = np.array([1,2,3,4,5])
print(arr[1:3])

[2 3]


In [112]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[4,3,5,6,7]])
print(arr[-1,-4])

3


In [115]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:3])
print(arr[:4])
print(arr[4:])
print(arr[1:6:2])
print(arr[::2])

[2 3]
[1 2 3 4]
[5 6 7 8]
[2 4 6]
[1 3 5 7]


In [114]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:6:2])

[2 4 6]


In [126]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
print(arr[::2])
print(arr[1::2])

[ 0  2  4  6  8 10]
[ 1  3  5  7  9 11]


In [135]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
arr.shape

[7 8 9]


(2, 5)

In [130]:
print(arr[:2,3])

[4 9]


In [134]:
arr = np.array([1,2,3,4,5,6,7,8])
x=arr.copy()
x[0]=40
print(arr)

print(x)
arr.shape

[1 2 3 4 5 6 7 8]
[40  2  3  4  5  6  7  8]


(8,)

In [6]:
a = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(a)
print('\n')
print(a[:,1:2])

[[11 22 33]
 [44 55 66]
 [77 88 99]]


[[22]
 [55]
 [88]]


In [15]:
a = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(a)
print('\n')
print(a[1::2,::2])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


[[15 21]
 [39 45]]


In [18]:
ar = np.array([[1,2,3],[4,5,6]])
for x in ar:
    print(x)

[1 2 3]
[4 5 6]


In [20]:
for x in ar:
    for y in x:
        print(y)

1
2
3
4
5
6


** *